name: devopsDb
services:
  sonar:
    container_name: devopsDb-sonarqube
    image: sonarqube:10.3.0-community
    environment:
      - SONAR_FORCEAUTHENTICATION=false
    ports:
      - 127.0.0.1:9001:9000
      - 127.0.0.1:9000:9000